SELECT min(temp) FROM weather;

-- TABLE DOES NOT ACTUALLY EXST
-- I'M ASSUMING A TABLE CALLED WEATHER WITH COLUMNS OF (LOCATION varChar(100), TEMP integer)
-- THIS WILL FIND THE LOWEST TEMPERATURE IN THE TABLE